### ISSUE TITLE
error "OpenCV 4.x+ requires enabled C++11 support"

### ISSUE THREAD

**Issue by megrimm** [avilleret/pix_opencv#14]
Gave compiling a whirl. Got lots of errors right off the bat. not sure how feasible we can get this compiling. Anyway here is first error:

In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:84:
/usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/cvdef.h:704:4: error: "OpenCV 4.x+ requires enabled
      C++11 support"
#  error "OpenCV 4.x+ requires enabled C++11 support"
   ^
In file included from pix_opencv_edge.cc:18:
In file included from ./pix_opencv_edge.h:20:
In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/core_c.h:48:
In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:126:
In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core.hpp:54:
In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/base.hpp:58:
In file included from /usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/cvstd.hpp:81:

**Comment by megrimm** [comment]
so this was all with opencv4 which is the default install with homebrew. i did install opencv@3 with homebrew and all seems to be compiling better but still an error that I will log as another issue.

**Comment by avilleret** [comment]
did you still get this error @megrimm with 4fc0db7b ?
