### ISSUE TITLE
no viable overloaded '='

### ISSUE THREAD

**Issue by megrimm** [avilleret/pix_opencv#17]
getting lots of these `no viable overloaded '='` and not quite sure how to fix. Anyway here is output for example

```
pix_opencv_calibration.cc:172:14: error: no viable overloaded '='
        patternSize = cv::Size( this->patternSize[0], this->patternSize[1] );
        ~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:1169:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'cv::Size' (aka 'Size_<int>') to 'const CvSize' for
      1st argument
typedef struct CvSize
               ^
/usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:1169:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'cv::Size' (aka 'Size_<int>') to 'CvSize' for 1st
      argument
pix_opencv_calibration.cc:173:13: error: no viable overloaded '='
        image_size = image.size();
        ~~~~~~~~~~ ^ ~~~~~~~~~~~~
/usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:1169:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'cv::Size' (aka 'Size_<int>') to 'const CvSize' for
      1st argument
typedef struct CvSize
               ^
/usr/local/Cellar/opencv/4.2.0_3/include/opencv4/opencv2/core/types_c.h:1169:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'cv::Size' (aka 'Size_<int>') to 'CvSize' for 1st
      argument
2 errors generated.:
```

**Comment by itaiSternberg** [comment]
Seems like the cpp file where the operator overloading was declared is missing

**Comment by megrimm** [comment]
ok getting somewhere i think. headers need to be updated to more recent version of opencv. this might be on all objects? so in pix_opencv_calibration.h line 19:

```
#ifndef _EiC
// #include "opencv2/core/core_c.h"
#include "opencv2/core.hpp"
// #include "opencv2/imgproc/imgproc_c.h"
#include "opencv2/imgproc.hpp"
#endif
```

**Comment by megrimm** [comment]
so it seems to me like older versions of opencv have headers like *_c.h and newer headers are like *.hpp. the pix_opencv objects are a few years old so rely on older opencv stuff. I think the older opencv headers are still there but all obects need to point to new opencv headers to compile against newer version.

i think?

**Comment by megrimm** [comment]
.... and i see some deprieciations listed here: https://answers.opencv.org/question/195784/proper-include-for-function/

so where there are errors involved in cv* the cv prefix can just be removed in most cases.

**Comment by itaiSternberg** [comment]
I tried to see if there's an operator overload pix_opencv_motempl.h file, I see this class inherits from the GemPixObj which is included with `#inlcude "Base/GemPixObj.h"`.  Maybe the file can't access gem properly?... maybe this is the problem.
I might be going in the wrong direction though

**Comment by megrimm** [comment]
for this specific error i had to update what header files the pix_opencv objects pointed to. so with this branch (https://github.com/megrimm/pd-pix_opencv/tree/opencv4) you should be able to see the changes I made. 

Take a look at https://github.com/megrimm/pd-pix_opencv/commit/94ee2641bf1f9055e087d874a090f03af3799371

you can see in red what I replaced with green.

**Comment by megrimm** [comment]
pix_opencv_calibration compiled BTW. im on to pix_opencv_camshift. also, i updated the Makefile.am file here:

https://github.com/megrimm/pd-pix_opencv/blob/opencv4/src/Makefile.am

if you want to update your you can so we are looking at the same objects at the same time. all it does is compile stuff alphabetically :)

also you can just pull my changes into your fork if you want. (https://stackoverflow.com/questions/42156971/git-pull-from-someone-elses-fork)

$ git remote add megrimm https://github.com/megrimm/pd-pix_opencv.git
$ git fetch megrimm
$ git checkout -b opencv4
$ git pull megrimm opencv4

**Comment by avilleret** [comment]
did you still got this error @megrimm with opencv4 branch ?

**Comment by avilleret** [comment]
I think this is fixed in opencv4 branch which should merge into master soon
