### ISSUE TITLE
Camshift

### ISSUE THREAD

**Issue by itaiSternberg** [avilleret/pix_opencv#18]
I think the problem with camShift is that it was heavily changed during the evolvement of  OpenCV.

2.4.13.7
https://docs.opencv.org/ref/2.4/d8/d92/tracking_8hpp.html#aa29607c5cb6f673707c4d8a17842ae1e

4.3.0
https://docs.opencv.org/4.3.0/dc/d6b/group__video__track.html#gaef2bd39c8356f423124f1fe7c44d54a1

Will look more into that tomorrow

**Comment by avilleret** [comment]
sure OpenCV API changed a lot since 2.4...

I just open a gitter room to talk about that if you want to join

https://gitter.im/pix_opencv/community

**Comment by avilleret** [comment]
camshift should now worrk again, please test on the Opencv4 branch
