### ISSUE TITLE
Can't compile because of FaceTracker

### ISSUE THREAD

**Issue by MarioMey** [avilleret/pix_opencv#22]
I'm trying to compile pix_opencv... and also compile everything I need. I'm in Buster.
- I compiled OpenCV4 successfully.
- I compiled cmake 3.18.2 successfully.
- I downloaded pix_opencv, branch opencv4.
- When compiling it, it says that FaceTracker is an empty folder.
- I cloned FaceTracker in that folder (https://github.com/avilleret/FaceTracker).
- Tried to compile again pix_opencv and it says:

```'pix_opencv' will be installed in ''
CMake Error at CMakeLists.txt:82 (add_subdirectory):
  The source directory

    /home/mario/src/pix_opencv/FaceTracker

  does not contain a CMakeLists.txt file.


Checking for module 'Gem'
  No package 'Gem' found
Configuring incomplete, errors occurred!
See also "/home/mario/src/pix_opencv/build/CMakeFiles/CMakeOutput.log".
```
- (*)
- So, I tried to compile FaceTracker. Error:

```
mario@debian:~/src/pix_opencv/FaceTracker$ make
g++ -MM -MT src/lib/Patch.o -MF src/lib/Patch.d -fPIC -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  `pkg-config --cflags opencv` -Iinclude/ src/lib/Patch.cc
g++ -fPIC -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  `pkg-config --cflags opencv` -Iinclude/ -c src/lib/Patch.cc -o src/lib/Patch.o
src/lib/Patch.cc: In member function ‘void FACETRACKER::Patch::Response(cv::Mat&, cv::Mat&)’:
src/lib/Patch.cc:163:7: error: ‘matchTemplate’ is not a member of ‘cv’
   cv::matchTemplate(I,_W,res_,CV_TM_CCOEFF_NORMED);
       ^~~~~~~~~~~~~
src/lib/Patch.cc: In member function ‘void FACETRACKER::MPatch::Write(std::ofstream&)’:
src/lib/Patch.cc:217:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
   for(int i = 0; i < (int)_p.size(); i++)_p[i].Write(s); return;
   ^~~
src/lib/Patch.cc:217:58: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   for(int i = 0; i < (int)_p.size(); i++)_p[i].Write(s); return;
                                                          ^~~~~~
make: *** [Makefile:59: src/lib/Patch.o] Error 1
```
I don't know what more to do.

I compiled opencv4 with `make install` but I don't know exactly where it is installed. Maybe is opencv4 path that it is not correctly configured in Makefile?

(*): also, error says that doesn't find Gem module. I configured its path to "/opt/purr-data/include/Gem" but the error is still there.

**Comment by avilleret** [comment]
`facetracker` is a submodule of `pix_opencv` repo, once you're on the `opencv4` branch, you should do : 

    git submodule update --init

and then run cmake again.

Concerning FaceTracker compilation, it could be due to several things, and the first thing to do is to get the right version, this is what the command above should do. Then CMake takes care of compiling it.

Concerning the Gem error, what is the error exactly ? and how did you "configured its path to....".
Gem comes with some pkgconfig script, if you installed it system wide (either in /usr or /usr/local) then pkgconfig should find it. If it don't, then you can tell cmake where it is with this kind of options :

    	cmake .. -DPUREDATA_INCLUDE_DIRS=/Applications/Pd-0.50-2.app/Contents/Resources/src/ \ 
			 -DGEM_INCLUDE_DIRS=~/Documents/Pd/externals/Gem/include/Gem

Which defines both puredata & Gem header location, of course you should adapt it.

**Comment by MarioMey** [comment]
Let's go step by step. First: thanks for answering me :D.

Now, I deleted everything inside FaceTracker (because I got source incorrectly), I did `git submodule update --init` and `cmake ..`. I get:

```
mario@debian:~/src/pix_opencv/build$ /home/mario/apps/cmake-3.18.2-Linux-x86_64/bin/cmake ..
-- Found OpenCV: /usr/local (found suitable version "4.4.0", minimum required is "4") found components: core imgproc video objdetect missing components: bgsegm
-- 'pix_opencv' will be installed in ''
-- Found OpenCV: /usr/local (found suitable version "4.4.0", minimum required is "4") found components: core imgproc objdetect videoio highgui 
-- Checking for module 'Gem'
--   No package 'Gem' found
-- Configuring done
CMake Error at FaceTracker/CMakeLists.txt:33 (add_library):
  Cannot find source file:

    /home/mario/src/pix_opencv/FaceTracker/src/lib/IO.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at FaceTracker/CMakeLists.txt:33 (add_library):
  No SOURCES given to target: FaceTracker


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

There's no IO.cc 🤷. However, looking at files inside the deleted folder (previous FaceTracker), I found `IO.cc` there.
What is the correct cource of FaceTrack?

**Comment by MarioMey** [comment]
I close this issue and I'll go on on #8 because it's the same problem. I'll write there my updates.
