### ISSUE TITLE
opencv_legacy module is deprecated

### ISSUE THREAD

**Issue by fdch** [avilleret/pix_opencv#6]
so it appears [here](http://answers.opencv.org/question/42622/opencv-30-deprecated-opencv_legacy-module/). I figure you already know this. Anyway, I just tried compiling on Debian stretch and failed with great success. How hard would it be to update? I'm a beginner here but I really like this lib.

**Comment by avilleret** [comment]
hi, sorry for the (too) late reply
I'm just updating it now to use OpenCV 3, some objects will be removed though (because some new ones have the same functionalities)

**Comment by avilleret** [comment]
I'm clonsing this issue since now it works with OpenCV3
If there are bugs with new version, fell free to open new issue

**Comment by fdch** [comment]
Excellent!! Thanks so much! Will try it out soon!
