### ISSUE TITLE
[compilation issue] opencv2/video/tracking_c.h: No such file or directory

### ISSUE THREAD

**Issue by fdch** [avilleret/pix_opencv#9]
Hi Antoine, 

I'm on El Capitan. I did ``brew install opencv`` and got  version ``4.0.1``

I compiled like this:  
```
./autogen.sh
./configure --with-pd=/Applications/Pd-0.49-1.app/Contents/Resources GEMPATH=~/Documents/Gem OPENCV_CFLAGS="`pkg-config --cflags opencv4`" OPENCV_LIBS="`pkg-config --libs opencv4`"
```
NOTE: I added ``GEMPATH`` because otherwise I got an error like ``pix_opencv_edge.h:24:10: fatal error: Base/GemPixObj.h: No such file or directory``

I then run ``make`` but the following error is reported:
```
In file included from pix_opencv_motempl.cc:18:
pix_opencv_motempl.h:22:10: fatal error: opencv2/video/tracking_c.h: No such file or directory
 #include "opencv2/video/tracking_c.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [pix_opencv_la-pix_opencv_motempl.lo] Error 1
make: *** [all-recursive] Error 1
```

What am I doing wrong? 

I tried removing ``pix_opencv_motempl`` from ``Makefile.am``, but I got a whole other set of errors.

Is it the ``opencv`` version? How would I install the correct one using brew?

Any help would be appreciated!

Best,

f

**Comment by fdch** [comment]
Ok, I switched to ``opencv 3.4.5`` and after compiling like this:
```
make clean
./autogen.sh
./configure --with-pd=/Applications/Pd-0.49-1.app/Contents/Resources GEMPATH=~/Documents/Gem OPENCV_CFLAGS="`pkg-config --cflags /usr/local/Cellar/opencv\@3/3.4.5/lib/pkgconfig/opencv.pc`" OPENCV_LIBS="`pkg-config --libs /usr/local/Cellar/opencv\@3/3.4.5/lib/pkgconfig/opencv.pc`"
make
```
I get the following error:

```
pix_opencv_motempl.cc: In member function 'virtual void pix_opencv_motempl::processRGBAImage(imageStruct&)':
pix_opencv_motempl.cc:195:21: error: 'CV_RGB' was not declared in this scope
             color = CV_RGB(255,255,255);
```

This error persists even if I remove ``pix_opencv_motempl`` from src/Makefile.am, since many objects use ``CV_RGB()``

**Comment by fdch** [comment]
I will try [this](https://github.com/openframeworks/openFrameworks/issues/6012#issuecomment-388443400)

**Comment by fdch** [comment]
The previous solution (changing ``CV_RGB`` to ``cv::Scalar``) did the trick. But, now several sources are including ``opencv2/legacy/legacy.hpp`` which afaict is not shipped with ``opencv3``.

I cloned the opencv github repo and checked out the 2.4 branch (since ``opencv/modules/legacy/include`` resides over there) and added the corresponding path to ``OPENCV_CFLAGS``. 

However, now I have a whole other stream of undeclared stuff errors, all coming from ``pix_opencv_lk`` which is the first object of many that require legacy.hpp.

The inclusion is done in several sources like this:
```
#ifndef _EiC
#include "opencv2/legacy/legacy.hpp"
#include "opencv2/video/tracking.hpp"

#endif
```

So, What is ``_EiC`` and can it be edited somehow to avoid this inclusion? Could this fix this issue?

**Comment by b01xy** [comment]
hello,

same error while trying to compile pix_opencv on debian 9 64 bits with Gem 0.94 compiled by hand :
`pix_opencv_motempl.h:22:38: fatal error: opencv2/video/tracking_c.h: Aucun fichier ou dossier de ce type`

I'll try to investigate
++
benjamin

**Comment by avilleret** [comment]
this is no more relevant with the opencv4 upgrade
